"""3D LUT lattice: .cube I/O, vectorized trilinear application, Laplacian.

Lattice layout: float32 array of shape (N, N, N, 3), indexed [r, g, b] ->
output RGB. The .cube file format iterates the FIRST (red) axis fastest;
`write_cube`/`read_cube` handle that ordering and it is locked by tests.
"""
from __future__ import annotations

import datetime
import json
from pathlib import Path

import numpy as np
import scipy.sparse as sp


def identity_lattice(n: int = 33) -> np.ndarray:
    ax = np.linspace(0.0, 1.0, n, dtype=np.float32)
    r, g, b = np.meshgrid(ax, ax, ax, indexing="ij")
    return np.stack([r, g, b], axis=-1)


def apply_trilinear(lattice: np.ndarray, rgb: np.ndarray) -> np.ndarray:
    """Apply a (N,N,N,3) lattice to rgb in [0,1], any leading shape."""
    n = lattice.shape[0]
    p = np.clip(rgb, 0.0, 1.0).astype(np.float32) * (n - 1)
    i0 = np.floor(p).astype(np.int32)
    np.minimum(i0, n - 2, out=i0)
    f = p - i0
    r0, g0, b0 = i0[..., 0], i0[..., 1], i0[..., 2]
    fr, fg, fb = f[..., 0:1], f[..., 1:2], f[..., 2:3]

    c000 = lattice[r0, g0, b0]
    c100 = lattice[r0 + 1, g0, b0]
    c010 = lattice[r0, g0 + 1, b0]
    c110 = lattice[r0 + 1, g0 + 1, b0]
    c001 = lattice[r0, g0, b0 + 1]
    c101 = lattice[r0 + 1, g0, b0 + 1]
    c011 = lattice[r0, g0 + 1, b0 + 1]
    c111 = lattice[r0 + 1, g0 + 1, b0 + 1]

    c00 = c000 + (c100 - c000) * fr
    c10 = c010 + (c110 - c010) * fr
    c01 = c001 + (c101 - c001) * fr
    c11 = c011 + (c111 - c011) * fr
    c0 = c00 + (c10 - c00) * fg
    c1 = c01 + (c11 - c01) * fg
    return c0 + (c1 - c0) * fb


def laplacian_matrix(n: int) -> sp.csr_matrix:
    """Sparse 6-neighbor graph Laplacian over an n^3 lattice (row-major r,g,b)."""
    idx = np.arange(n ** 3).reshape(n, n, n)
    rows, cols = [], []
    for axis in range(3):
        a = np.take(idx, np.arange(n - 1), axis=axis).ravel()
        b = np.take(idx, np.arange(1, n), axis=axis).ravel()
        rows.append(a)
        cols.append(b)
    rows = np.concatenate(rows)
    cols = np.concatenate(cols)
    data = np.ones(len(rows))
    adj = sp.coo_matrix((data, (rows, cols)), shape=(n ** 3, n ** 3))
    adj = adj + adj.T
    deg = sp.diags(np.asarray(adj.sum(axis=1)).ravel())
    return (deg - adj).tocsr()


def smooth_lattice(lattice: np.ndarray, lam: float = 0.5) -> np.ndarray:
    """Solve (I + lam*L) t = t_raw per channel: mild Laplacian smoothing."""
    n = lattice.shape[0]
    L = laplacian_matrix(n)
    A = (sp.eye(n ** 3) + lam * L).tocsc()
    solve = sp.linalg.factorized(A)
    out = np.empty_like(lattice)
    flat = lattice.reshape(-1, 3)
    for c in range(3):
        out.reshape(-1, 3)[:, c] = solve(flat[:, c].astype(np.float64))
    return out


def write_cube(
    path: str | Path,
    lattice: np.ndarray,
    title: str,
    comments: dict | None = None,
) -> None:
    n = lattice.shape[0]
    lines = [f'TITLE "{title}"']
    lines.append(f"# Generated by silbersalz-look on {datetime.date.today().isoformat()}")
    lines.append("# Input:  Silbersalz flat-scan code values [0,1] (Display P3 tagged)")
    lines.append("# Output: graded display code values (Display P3)")
    for k, v in (comments or {}).items():
        lines.append(f"# {k}: {v}")
    lines.append(f"LUT_3D_SIZE {n}")
    lines.append("DOMAIN_MIN 0.0 0.0 0.0")
    lines.append("DOMAIN_MAX 1.0 1.0 1.0")
    # .cube iterates red fastest: index order b, g, r in the outer loops.
    vals = np.transpose(lattice, (2, 1, 0, 3)).reshape(-1, 3)
    for v in vals:
        lines.append(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    Path(path).write_text("\n".join(lines) + "\n")


def read_cube(path: str | Path) -> tuple[np.ndarray, str]:
    n = None
    title = ""
    vals = []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.upper().startswith("TITLE"):
            title = line.split(None, 1)[1].strip().strip('"')
        elif line.upper().startswith("LUT_3D_SIZE"):
            n = int(line.split()[1])
        elif line.upper().startswith(("DOMAIN_MIN", "DOMAIN_MAX", "LUT_1D")):
            continue
        else:
            parts = line.split()
            if len(parts) == 3:
                vals.append([float(p) for p in parts])
    if n is None or len(vals) != n ** 3:
        raise ValueError(f"invalid .cube file: {path}")
    arr = np.asarray(vals, dtype=np.float32).reshape(n, n, n, 3)
    return np.transpose(arr, (2, 1, 0, 3)), title


def write_stats_sidecar(cube_path: str | Path, stats: dict) -> Path:
    p = Path(cube_path).with_suffix(".stats.json")
    p.write_text(json.dumps(stats, indent=2, sort_keys=True))
    return p


def read_stats_sidecar(cube_path: str | Path) -> dict | None:
    p = Path(cube_path).with_suffix(".stats.json")
    if p.exists():
        return json.loads(p.read_text())
    return None


def write_hald_png(path: str | Path, lattice: np.ndarray, level: int = 8) -> None:
    """HaldCLUT PNG (level 8 = 64^3 samples, 512x512) from a lattice, for
    RawTherapee / G'MIC and other apps that don't read .cube."""
    from PIL import Image

    n = level * level
    ax = np.linspace(0.0, 1.0, n, dtype=np.float32)
    b, g, r = np.meshgrid(ax, ax, ax, indexing="ij")  # hald order: R fastest, then G, then B
    rgb = np.stack([r, g, b], axis=-1).reshape(-1, 3)
    out = apply_trilinear(lattice, rgb)
    img = (np.clip(out, 0, 1) * 255 + 0.5).astype(np.uint8).reshape(n * level, n * level, 3)
    Image.fromarray(img).save(str(path), "PNG")
